name: CI Pipeline for Metric & Health Services

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint-and-typecheck:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: TypeScript type check
        run: npx tsc --noEmit

  test-services:
    name: Test Metric & Health Services
    runs-on: ubuntu-latest
    needs: lint-and-typecheck

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Test Metrics Service (Controller + Service)
      - name: Test Metrics Controller
        run: npm test metricController.test.ts

      - name: Test Metrics Service
        run: npm test metricsService.test.ts
        if: success() || failure()

      # Test Health Service (Controller + Service)
      - name: Test Health Controller
        run: npm test healthController.test.ts
        if: success() || failure()

      - name: Test Health Service
        run: npm test healthService.test.ts
        if: success() || failure()

      # Run all unit tests with coverage
      - name: Run all unit tests with coverage
        run: npm run test:coverage

      - name: Check coverage threshold
        run: |
          echo " Coverage report generated"
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test-services

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Verify build output
        run: |
          echo " Build completed successfully"
          ls -la dist/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [lint-and-typecheck, test-services, build]
    if: always()

    steps:
      - name: Check pipeline status
        run: |
          echo "================================"
          echo " CI Pipeline Summary"
          echo "================================"
          echo "✅ Lint & Type Check: ${{ needs.lint-and-typecheck.result }}"
          echo "✅ Tests: ${{ needs.test-services.result }}"
          echo "✅ Build: ${{ needs.build.result }}"
          echo "================================"

          if [ "${{ needs.lint-and-typecheck.result }}" != "success" ] || \
             [ "${{ needs.test-services.result }}" != "success" ] || \
             [ "${{ needs.build.result }}" != "success" ]; then
            echo " Pipeline failed!"
            exit 1
          else
            echo "✅ All checks passed!"
          fi
